### ISSUE TITLE
yii\base\InvalidParamException with message "Response content must not be an array."

### ISSUE THREAD

**Issue by johnluxor** [2amigos/yii2-grid-view-library#8]
Last commit has broken code in Toggle Action class. 
If model was saved successfully then will not set response format to JSON and I got error

yii\base\InvalidParamException with message "Response content must not be an array."

**Comment by kepingatp** [comment]
Hi sir, I got the same error, and I just add the code like your suggestion. But I still got the same. Can you help me, may be you can check my code. Because I'm not sure I've put the code in the right place.

This is my code [https://github.com/kepingatp/pstk/blob/master/ToggleAction.php](url)
Thanks.

**Comment by VBetsun** [comment]
try to use this before return
\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
